### ISSUE TITLE
CakePHP 4 Support

### ISSUE THREAD

**Issue by josephshanak** [tyrellsys/cakephp3-aws-ses-transport#11]
I am currently using this plugin in a CakePHP3 application that is preparing to upgrade to CakePHP 4, and I would like to know what your plans are for maintaining this plugin now that CakePHP 4 is out. Are there plans on updating this plugin to support CakePHP 4?

**Comment by mtak3** [comment]
Already supports CakePHP4.
https://github.com/tyrellsys/cakephp3-aws-ses-transport/pull/10

I created a release `4.0.0`  for CakePHP4.
https://packagist.org/packages/tyrellsys/cakephp3-aws-ses-transport#4.0.0

**Comment by josephshanak** [comment]
> Already supports CakePHP4.
> #10
> 
> I created a release `4.0.0` for CakePHP4.
> https://packagist.org/packages/tyrellsys/cakephp3-aws-ses-transport#4.0.0

I guess I missed that PR when I was looking to see if there was an upgrade path.

Thank you for creating the release! Should I leave this issue open until the PR is merged?
